export const travelFacts = [
  "Did you know? France is the most visited country in the world, with over 89 million tourists annually.",
  "The shortest commercial flight in the world lasts just 57 seconds, between the Scottish islands of Westray and Papa Westray.",
  "Japan has the most vending machines per capita—about 1 for every 23 people!",
  "Machu Picchu was lost to the outside world until American explorer Hiram Bingham 'discovered' it in 1911.",
  "There are no mosquitoes in Iceland. The country's unique oceanic climate keeps them away.",
  "The Great Wall of China is made with sticky rice! The mortar used to build it included a mixture of sticky rice flour and slaked lime.",
  "Canada has more lakes than the rest of the world combined.",
  "There are more ancient pyramids in Sudan than in Egypt.",
  "The entire country of Monaco is smaller than Central Park in New York City.",
  "Saudi Arabia has to import camels and sand from Australia. Yes, sand.",
  "Our AI is checking local opening times and typical dwell times for your activities...",
  "We are mapping out the most efficient routes so you spend less time in transit...",
  "Optimizing for your preferred walking pace and dietary restrictions...",
  "The deepest place on Earth is the Mariana Trench in the Pacific Ocean.",
  "Alaska has more coastline than all other U.S. states combined.",
  "The oldest continuously operating hotel is in Japan. Nishiyama Onsen Keiunkan has been open since 705 AD!",
  "Finding the best local hidden gems that fit your vibe...",
  "Checking historical weather patterns for your travel dates...",
];
